"""added sticker details to |assets| table

Revision ID: 0f9f98e44490
Revises: ebfcc02fe17c
Create Date: 2025-05-06 15:27:09.246363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9f98e44490'
down_revision = 'ebfcc02fe17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticker_capsule', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sticker_effect', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('sticker_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sticker_event', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sticker_team', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sticker_player', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('sticker_player')
        batch_op.drop_column('sticker_team')
        batch_op.drop_column('sticker_event')
        batch_op.drop_column('sticker_type')
        batch_op.drop_column('sticker_effect')
        batch_op.drop_column('sticker_capsule')

    # ### end Alembic commands ###
