"""Finalized |type| ENUM values, added ENUM to |category|

Revision ID: 11d79697293d
Revises: 2a0b9bcd8549
Create Date: 2025-04-30 13:53:32.906586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11d79697293d'
down_revision = '2a0b9bcd8549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('Normal', 'Souvenir', 'StatTrak', 'Star', 'StarStatTrak', name='category'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Normal', 'Souvenir', 'StatTrak', 'Star', 'StarStatTrak', name='category'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
