"""Added icon_url to listings table

Revision ID: 1912e39d3dc9
Revises: 5c8243724840
Create Date: 2025-04-25 05:36:09.061507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912e39d3dc9'
down_revision = '5c8243724840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('icon_url')

    # ### end Alembic commands ###
