"""Changed name of |rarity| column |quality| in |assets| table

Revision ID: 2a0b9bcd8549
Revises: 46a729cbfb48
Create Date: 2025-04-29 13:52:43.098611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a0b9bcd8549'
down_revision = '46a729cbfb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.String(length=32), nullable=True))
        batch_op.drop_column('rarity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('quality')

    # ### end Alembic commands ###
