"""added |color| column

Revision ID: 469a76fc358f
Revises: 11d79697293d
Create Date: 2025-04-30 19:35:38.959760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469a76fc358f'
down_revision = '11d79697293d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
