"""changed nullable=False to nullable=True, column |rarity| in table |assets|

Revision ID: 46a729cbfb48
Revises: 923e1e15eade
Create Date: 2025-04-29 11:23:06.454793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46a729cbfb48'
down_revision = '923e1e15eade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Weapon', 'Case', 'Sticker', 'Agent', 'Music Kit', 'Tool', 'Patch', 'Graffiti', 'Pass', 'Collectible', 'Charm', 'Gift'),
               nullable=False)
        batch_op.alter_column('rarity',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('rarity',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Weapon', 'Case', 'Sticker', 'Agent', 'Music Kit', 'Tool', 'Patch', 'Graffiti', 'Pass', 'Collectible', 'Charm', 'Gift'),
               nullable=True)

    # ### end Alembic commands ###
