"""Added listings table - beta

Revision ID: 5c8243724840
Revises: 
Create Date: 2025-04-21 07:03:26.534817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c8243724840'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
