"""Indexed |steam_id| column in |users| table

Revision ID: 85a4ff67aed6
Revises: 0f9f98e44490
Create Date: 2025-05-08 13:11:53.223804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a4ff67aed6'
down_revision = '0f9f98e44490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('steam_id')
        batch_op.create_index(batch_op.f('ix_users_steam_id'), ['steam_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_steam_id'))
        batch_op.create_index('steam_id', ['steam_id'], unique=True)

    # ### end Alembic commands ###
