"""added |gift| enum option in column |type| in table |assets|

Revision ID: 923e1e15eade
Revises: e4c91141c3a5
Create Date: 2025-04-29 11:20:00.549753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '923e1e15eade'
down_revision = 'e4c91141c3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Weapon', 'Case', 'Sticker', 'Agent', 'Music Kit', 'Tool', 'Patch', 'Graffiti', 'Pass', 'Collectible', 'Charm'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Weapon', 'Case', 'Sticker', 'Agent', 'Music Kit', 'Tool', 'Patch', 'Graffiti', 'Pass', 'Collectible', 'Charm'),
               nullable=True)

    # ### end Alembic commands ###
