"""testing new static |assets| table

Revision ID: e4c91141c3a5
Revises: fde627536ce9
Create Date: 2025-04-29 10:21:37.363859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c91141c3a5'
down_revision = 'fde627536ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('Weapon', 'Case', 'Sticker', 'Agent', 'Music Kit', 'Tool', 'Patch', 'Graffiti', 'PassCollectible', 'Charm', name='type'), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('rarity', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('weapon_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('skin', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('exterior', sa.Enum('Factory New', 'Minimal Wear', 'Field-Tested', 'Well-Worn', 'Battle-Scarred', 'Not Painted', name='exterior'), nullable=True))
        batch_op.add_column(sa.Column('collection', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('team', sa.Enum('Counter-Terrorist', 'Terrorist', 'Both Teams', name='team'), nullable=True))
        batch_op.add_column(sa.Column('min_float', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_float', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('icon_url', sa.String(length=512), nullable=False))
        batch_op.drop_column('skin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('icon_url')
        batch_op.drop_column('max_float')
        batch_op.drop_column('min_float')
        batch_op.drop_column('team')
        batch_op.drop_column('collection')
        batch_op.drop_column('exterior')
        batch_op.drop_column('skin')
        batch_op.drop_column('weapon_type')
        batch_op.drop_column('rarity')
        batch_op.drop_column('category')
        batch_op.drop_column('type')
        batch_op.drop_column('id')

    op.create_table('skins',
    sa.Column('skin_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('skin_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
